#!/bin/bash
# Complete Git Push & Merge Guide
# Copy and paste these commands step by step

echo "=========================================="
echo "Horns & Heritage - GitHub Merge & Deploy"
echo "=========================================="
echo ""

# ========================================
# STEP 1: CLONE YOUR REPOSITORY
# ========================================
echo "STEP 1: Clone Your GitHub Repository"
echo "======================================"
echo ""
echo "Run this command:"
echo ""
echo "  git clone https://github.com/TWEBAZEHILLARY/horns-heritage.git"
echo ""
echo "This creates a folder called 'horns-heritage' with your repo files"
echo ""
echo "Then navigate into it:"
echo "  cd horns-heritage"
echo ""
read -p "Press Enter after running these commands..."

# ========================================
# STEP 2: COPY FILES FROM WORKSPACE
# ========================================
echo ""
echo "STEP 2: Copy Files from Workspace"
echo "=================================="
echo ""
echo "You need to copy these files from the workspace to your cloned repo:"
echo ""
echo "Files to copy:"
echo "  ✓ wrangler.toml"
echo "  ✓ package.json"
echo "  ✓ .gitignore"
echo "  ✓ src/index.js (copy src folder)"
echo "  ✓ .github/workflows/deploy.yml (copy .github folder)"
echo "  ✓ public/* (copy entire public folder)"
echo "  ✓ assets/* (copy to assets folder)"
echo "  ✓ _ds/* (copy to _ds folder)"
echo ""
echo "HOW TO COPY:"
echo ""
echo "Option A: Using File Manager (Easiest)"
echo "  1. Open File Manager / Finder"
echo "  2. Navigate to your workspace folder"
echo "  3. Find the files/folders listed above"
echo "  4. Drag them into the 'horns-heritage' folder you just cloned"
echo "  5. Replace if asked"
echo ""
echo "Option B: Using Terminal/Command Line"
echo "  macOS/Linux:"
echo "    cp -r ~/workspace/public/* ~/horns-heritage/public/"
echo "    cp -r ~/workspace/assets/* ~/horns-heritage/assets/"
echo "    cp ~/workspace/wrangler.toml ~/horns-heritage/"
echo "    cp ~/workspace/package.json ~/horns-heritage/"
echo "    etc..."
echo ""
echo "  Windows (PowerShell):"
echo "    Copy-Item -Path 'C:\\workspace\\public\\*' -Destination 'C:\\horns-heritage\\public\\' -Recurse"
echo "    Copy-Item -Path 'C:\\workspace\\wrangler.toml' -Destination 'C:\\horns-heritage\\'"
echo "    etc..."
echo ""
read -p "Press Enter after copying files..."

# ========================================
# STEP 3: CHECK FILES WERE COPIED
# ========================================
echo ""
echo "STEP 3: Verify Files Were Copied"
echo "================================="
echo ""
echo "List files in your repo to verify:"
echo ""
echo "  ls -la"
echo ""
echo "You should see:"
echo "  ✓ wrangler.toml"
echo "  ✓ package.json"
echo "  ✓ .gitignore"
echo "  ✓ src/ (folder)"
echo "  ✓ public/ (folder)"
echo "  ✓ .github/ (folder)"
echo ""
read -p "Press Enter after verifying..."

# ========================================
# STEP 4: STAGE FILES FOR GIT
# ========================================
echo ""
echo "STEP 4: Stage Files (git add)"
echo "============================="
echo ""
echo "Tell git to track all your changes:"
echo ""
echo "  git add ."
echo ""
echo "This stages all files for commit"
echo ""
read -p "Press Enter after running git add..."

# ========================================
# STEP 5: COMMIT CHANGES
# ========================================
echo ""
echo "STEP 5: Commit Changes (git commit)"
echo "==================================="
echo ""
echo "Create a commit with your changes:"
echo ""
echo "  git commit -m \"Merge: Add deployment configuration and CI/CD pipeline"
echo ""
echo "  - Move all project files to repository root"
echo "  - Add wrangler.toml for Cloudflare Workers"
echo "  - Add GitHub Actions CI/CD workflow"
echo "  - Add comprehensive deployment documentation\""
echo ""
echo "This saves your changes locally"
echo ""
read -p "Press Enter after committing..."

# ========================================
# STEP 6: PUSH TO GITHUB
# ========================================
echo ""
echo "STEP 6: Push to GitHub (git push)"
echo "=================================="
echo ""
echo "Send your changes to GitHub:"
echo ""
echo "  git push origin master"
echo ""
echo "If you get an error about 'main' vs 'master':"
echo "  Try: git push origin main"
echo ""
echo "This uploads your files to GitHub"
echo ""
read -p "Press Enter after pushing..."

# ========================================
# STEP 7: VERIFY ON GITHUB
# ========================================
echo ""
echo "STEP 7: Verify on GitHub"
echo "========================"
echo ""
echo "Check that your files are now on GitHub:"
echo ""
echo "1. Go to: https://github.com/TWEBAZEHILLARY/horns-heritage"
echo "2. You should see these files at the root level:"
echo "   ✓ wrangler.toml"
echo "   ✓ package.json"
echo "   ✓ .gitignore"
echo "   ✓ src/"
echo "   ✓ public/"
echo "   ✓ .github/"
echo ""
echo "3. Click on 'Code' tab to verify"
echo ""
read -p "Press Enter after verifying on GitHub..."

# ========================================
# STEP 8: ADD GITHUB SECRETS
# ========================================
echo ""
echo "STEP 8: Add GitHub Secrets"
echo "=========================="
echo ""
echo "Add your Cloudflare credentials to GitHub:"
echo ""
echo "1. Go to: https://github.com/TWEBAZEHILLARY/horns-heritage/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo ""
echo "Add Secret 1:"
echo "  Name: CLOUDFLARE_API_TOKEN"
echo "  Value: (Paste your API token from Cloudflare)"
echo "  Click 'Add secret'"
echo ""
echo "Add Secret 2:"
echo "  Name: CLOUDFLARE_ACCOUNT_ID"
echo "  Value: (Paste your Account ID from Cloudflare)"
echo "  Click 'Add secret'"
echo ""
read -p "Press Enter after adding secrets..."

# ========================================
# STEP 9: TEST THE PIPELINE
# ========================================
echo ""
echo "STEP 9: Test Automatic Deployment"
echo "=================================="
echo ""
echo "Make a small change and push to test CI/CD:"
echo ""
echo "  1. Edit a file (e.g., add a comment to public/index.html)"
echo "  2. Run:"
echo ""
echo "     git add ."
echo "     git commit -m \"Test: Verify CI/CD pipeline\""
echo "     git push origin master"
echo ""
echo "  3. Go to: https://github.com/TWEBAZEHILLARY/horns-heritage/actions"
echo "  4. Watch 'Deploy to Cloudflare Workers' workflow run"
echo "  5. Wait for it to complete (2-3 minutes)"
echo "  6. Once it shows ✅ green, check your site:"
echo "     https://horns-heritage.workers.dev"
echo ""
read -p "Press Enter when deployment is complete..."

# ========================================
# DONE!
# ========================================
echo ""
echo "=========================================="
echo "✅ SETUP COMPLETE!"
echo "=========================================="
echo ""
echo "Your site is now set up for automatic deployments!"
echo ""
echo "From now on, just do this to deploy:"
echo ""
echo "  1. Make changes to your files"
echo "  2. git add ."
echo "  3. git commit -m \"Your message\""
echo "  4. git push origin master"
echo "  5. Automatic deployment happens!"
echo ""
echo "Check deployment status:"
echo "  https://github.com/TWEBAZEHILLARY/horns-heritage/actions"
echo ""
echo "View your live site:"
echo "  https://horns-heritage.workers.dev"
echo ""
